---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: alertmanager
  type: LoadBalancer 
  ports:
    - port: 9093
      targetPort: 9093
